add exp_separator, SOI and EOI pest rules.
iankressin/eql pull request #26
Opened 2024-08-08 19:30 UTC by yulesa

# Summary

- Add SOI and EOI pest expressions to the `.pest` file. This will force the file to have only valid EQL expression as defined by the parser.
- Add `exp_separators` ignored entities to the pest rules so the user can choose to use or not use them or even make inline multiple EQL expressions.

## Associated issue
https://github.com/iankressin/eql/issues/25#issue-2456454195

2024-08-08 19:53 UTC, yulesa commented
## Successful Run Printscreen

![image](https://github.com/user-attachments/assets/f1b14566-9353-40e1-9927-23ed2aead58f)
![image](https://github.com/user-attachments/assets/58beae4c-3b96-4fe0-b1b9-f690d31cefc8)

2024-08-09 23:45 UTC, iankressin requested changes

2024-08-09 23:45 UTC, iankressin commented on crates/core/src/interpreter/frontend/productions.pest
> +eoi = _{ !ANY } //silent EOI
why defining a local `eoi` when pest provides an EOI?

also it'd be nice moving `exp_separator` and `eoi` under `//Helpers`

2024-08-09 23:45 UTC, iankressin commented on crates/core/src/interpreter/frontend/productions.pest
> +WHITESPACE = _{ " " | "\t" | NEWLINE}
```suggestion
WHITESPACE = _{ " " | "\t" | NEWLINE }
```

nice catch

2024-08-10 10:36 UTC, yulesa commented on crates/core/src/interpreter/frontend/productions.pest
> +eoi = _{ !ANY } //silent EOI
SOI and EOI have different behaviors. While SOI is silent by default, EOI is not and will generate a pest token (a key in JSON). This was causing the program to fail because downstream this pest token was not being handled.
We could solve it in two ways: either make a "workaround" for it to be silent, like I did, or handle it downstream in the frontend logic.

After I thought I could also make the EOI silent by making eoi = _{ EOI }, but I haven't tried it.

I understood the error and got the idea of the silent EOI in this discussion here: https://github.com/pest-parser/pest/issues/304

2024-08-10 11:07 UTC, iankressin commented on crates/core/src/interpreter/frontend/productions.pest
> +eoi = _{ !ANY } //silent EOI
> We could solve it in two ways: either make a "workaround" for it to be silent, like I did, or handle it downstream in the frontend logic.

I much rather go for the workaround and keep `parser.rs` cleaner. Your solution is fine.

> After I thought I could also make the EOI silent by making eoi = _{ EOI }, but I haven't tried it.

I though the same thing way I saw that production. `eoi = _{ EOI }` it's easier to understand at first glance. 
Or even `SILENT_EOI = _{ EOI }`, so we don't leave room for interpretation.

2024-08-12 13:19 UTC, yulesa commented on crates/core/src/interpreter/frontend/productions.pest
> +eoi = _{ !ANY } //silent EOI
`_{ EOI }` does not work. It still created a token, which failed later on.
![image](https://github.com/user-attachments/assets/d456b2a2-53e8-44ad-9239-622cc6bea8c2)

Changed the name to `silent_eoi` and moved it to helpers.

2024-08-12 13:41 UTC, merged