Add logs
iankressin/eql pull request #35
Opened 2024-08-14 13:16 UTC by yulesa

2024-08-27 02:17 UTC, iankressin requested changes

2024-08-27 02:17 UTC, iankressin commented on crates/core/src/interpreter/frontend/productions.pest
> +account_id = _{ address | ens }
why have you silenced `account_id`?

2024-08-27 02:17 UTC, iankressin commented on crates/core/src/interpreter/frontend/productions.pest
> +solidity_type = _{ ("uint" ~ size | "uint[]" | "uint" ) | ("bytes" ~ size | "bytes[]" | "bytes" ) | ("int" ~ size | "int[]" | "int" ) | ("address" ~ "[]"*) | "string" | "bool" }
shouldn't we extend this to all sol types?

2024-08-27 02:17 UTC, iankressin commented on crates/core/src/interpreter/frontend/productions.pest
> +size = _{integer ~ "[]"*}
not sure we should go on with this. this basically allows for any uint size, even the ones that doesn't exist.

we're also not checking this in run-time, so if someone uses an arbitrary type we end up with an undefined behavior

2024-08-27 17:26 UTC, yulesa commented on crates/core/src/common/entity_filter.rs
> +}
What I've done, and also what feels more legible to me, is one data type (struct in this case) and all its implementations, another data type and its implementations, etc.
I can change this flow, but it's not clear to me what you've meant.
Maybe a better idea is to move all error types to their own lib.

2024-08-27 18:14 UTC, yulesa commented on crates/core/src/interpreter/frontend/parser.rs
> +    //Need to run this test, because I think it will fail.
Yes. I wrote the comment on the first round of modifications because I knew I had to return and fix it. I did, but I did not remove the comment.

2024-08-27 18:30 UTC, yulesa commented on crates/core/src/interpreter/frontend/productions.pest
> +account_id = _{ address | ens }
I've silenced everything that is not being used as a pair_rule matching. It makes the code simpler because you don't need to deal with multiple nested pairs.

2024-08-27 18:40 UTC, yulesa commented on crates/core/src/interpreter/frontend/productions.pest
> +solidity_type = _{ ("uint" ~ size | "uint[]" | "uint" ) | ("bytes" ~ size | "bytes[]" | "bytes" ) | ("int" ~ size | "int[]" | "int" ) | ("address" ~ "[]"*) | "string" | "bool" }
What is missing?
Tupples are missing, but I could not make a pest code to support it without breaking regular expressions. Signatures like: `send(string,bytes,(address,uint128)[],string,(uint64,uint64),uint64)`

2024-08-27 19:11 UTC, yulesa commented on crates/core/src/interpreter/backend/execution_engine.rs
> +        println!("{:#?}", execution_result);
Uhm. I misunderstood the limitation of 10k blocks. Only a range needs to be limited to 10k blocks.  Not the look back.
Fixed.

2024-08-27 19:55 UTC, yulesa commented on crates/core/src/interpreter/backend/execution_engine.rs
> +        println!("{:#?}", execution_result);
fixed.

2024-08-28 11:20 UTC, iankressin commented on crates/core/src/common/entity_filter.rs
> +}
>  but it's not clear to me what you've meant
I mean it's a common pattern to declare all enums and types before they're actually used in a file. Here you're defining in the bottom of the file, after the first occurrence.

> Maybe a better idea is to move all error types to their own lib.
I don't think so. This error is local to this file, and it's not being used anywhere else.

2024-08-28 11:26 UTC, iankressin commented on crates/core/src/interpreter/frontend/productions.pest
> +size = _{integer ~ "[]"*}
I'm rethinking this, and I think we can move on as is.

2024-08-28 11:31 UTC, iankressin commented on crates/core/src/interpreter/frontend/productions.pest
> +solidity_type = _{ ("uint" ~ size | "uint[]" | "uint" ) | ("bytes" ~ size | "bytes[]" | "bytes" ) | ("int" ~ size | "int[]" | "int" ) | ("address" ~ "[]"*) | "string" | "bool" }
I'm sorry, the comment above was far from being clear.

I was talking about the array types of `bool` and `string`
`bool[]`, `string[]`,

2024-08-28 11:34 UTC, iankressin approved these changes

2024-08-28 11:37 UTC, merged