Add support to EntityId Lists
iankressin/eql pull request #39
Opened 2024-09-04 21:16 UTC by yulesa

# Summary

This PR adds support for lists in the EntidyId field, allowing users to fetch data for multiple accounts, blocks, or transactions in a single query.
Examples:
```
GET nonce, balance, code FROM 
  account 
     0x1234567890123456789012345678901234567890,
     0x1234567890123456789012345678901234567890
ON eth

GET nonce, balance FROM account vitalik.eth, yulesa.eth ON eth

GET timestamp FROM block 1:10, 20000000

GET from, to FROM 
  tx 
    0x9a14a38f4a53141edf5879cad97519455b45373a12f029aa2726f02845557d78, 
    0xa6fcabb9aff0c4a4fe42ccd41d02fb9129aaa91ec57d48b7510fc6b39de38c90 
ON eth
```

## Related Issue

No issue

## Technical details

### productions.pest
The pest file implements some new rules. `entity_id` are lists (`entity_id = { tx_id_list | account_id_list | block_id_list }`). Block, account and transactions now implement a list, such as 
`_{ account_field ~ ("," ~ WHITESPACE* ~ account_field)* }`.  IDs are not silent anymore since that's what the parser will look for to create a rule (e.g. `account_id = { address | ens }`)

### parser.rs
Instead of calling the `try_into` method on the Pair's string, we call it in the whole pair. Same functionality we implemented before for entity_filters. Fixed the tests, since `EntityId` is now a vec.

### common folder
`entity_id` in both EQLBuilder (query_builder.rs) and GetExpression (types.rs) structs are vecs. 
In `entity_id.rs`:
- Moved enum `EntityIdError` up in the file.
- As already mentioned, `try_from` now receives the whole pair and creates the EntityId from it. It looks at the pair-rule (e.g. account_id) to select the variant.
- Impl methods that would parse the EntityId into their inner types were moved to the backend, since it makes much more sense to do them in the resolving of each entity.

### execution_engine.rs
It suffered a significant overhaul, drastically simplifying it and moving the logic to resolve each entity type to dedicated files. This included the `get_transaction`, `get_logs`, and `get_accounts` functions that were moved to their own files. The `run_get_expr` function now only matches each entity type and calls the respective `resolve_[entity]_query` function with EntityId vec as a param. Fields, Filters, and Provider are still being parsed here. 
Small change in blocks logic, that already supports filters. If a filter instead of an entity_id is present, we translate the filter to a `entity_id` and handle the case normally.

### Resolvers
Like previously we had a file to resolve blocks, now we have one for each entity. I took the liberty of renaming them from `block_resolver` -> `resolve_block`, because this makes similar files stay grouped in the tree.
Logic from `execution_engine` was moved to these files with one major change: since we now have multiple entity_ids, we need to make requests for each one of them. The logic goes as follows:
- we create a list of futures (for each request). 
  - for each entity_id, we check if it belongs to the same entity type we are getting (match). This removes one of the TODOs in the semantic_analyzer (need to rename this file).
  - parse the entity_id (impl methods moved from EntityId).
  - call the get function (moved from execution_engine).
 - Each logic above is added to the future list.
- We then execute all futures concurrently and collect the results., joining them all together in the result vec. I had to use a new library to make this automatically ([futures](https://docs.rs/futures/0.3.5/futures/index.html)). I couldn't figure if tokio could handle this without introducing this new dependency.

Ps. Logs do not require concurrency, since we do not support lists for it. The previous logic was mostly unaltered.

## PR Checklist

-   [x] Added Tests
-   [x] Cargo Tests Passing
-   [ ] Added Documentation
-   [ ] Breaking changes

## Screenshots (if applicable)

![image](https://github.com/user-attachments/assets/c0382a11-c365-4d46-94e9-d3bedb62a7bd)

2024-09-09 19:00 UTC, iankressin commented
@yulesa

Before jumping into code review we have two problems to fix:

There's one test failing:
![image](https://github.com/user-attachments/assets/ea6e2857-f128-4e07-8878-a0e4901cd715)
  
  
The REPL is printing the results side-by-side, when it should be stacked
![image](https://github.com/user-attachments/assets/62047b5d-ecb9-4f19-a5ee-c576d93f4fac)

2024-09-09 20:28 UTC, yulesa commented
Fixed. We can't test the `GET * FROM account` results because it fetches the last block, and that can change the values.

2024-09-09 21:27 UTC, iankressin requested changes

2024-09-09 21:27 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_block.rs
> +        block_futures.push(block_future);
I rather having a doc for a function instead of a comment for each line. This can be quite distracting, and with function-level docs we can use the LSP to quickly learn what a function does.

You should only document really specific decision, that readers wouldn't get right away. Documenting common constructions makes the comments redundant.  

To be honest, I don't think the section above needs any kind of inline documentation, since all the operation and variable name give all the context one need to understand the body of the function.

This comment can be extended for the rest of this PR

2024-09-09 21:27 UTC, iankressin commented on crates/core/src/common/entity_id.rs
Parsing ids and ranges looks way better now. Good job

2024-09-09 21:27 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_transaction.rs
> +    // InvalidAddress,
remove

2024-09-09 21:27 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_logs.rs
> +    // InvalidAddress,
remove

2024-09-09 21:27 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_logs.rs
> +    MismatchEntityAndEntityId,
since now we have a specific error for this module we can add more context here, since the error message doesn't need be generic anymore. 

```suggestion
    #[error("Entity id {0} can't be used to identify Log")]
    MismatchEntityAndEntityId(String),
```

2024-09-09 21:27 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_logs.rs
> +        return Err("No logs found".into()); // Check if this is the best approach for no logs return. I understand it shouldn't panic.
should return a variant from the `LogResolverErrors`

2024-09-09 21:27 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_transaction.rs
> +    EnsResolution,
We don't need this variant here

2024-09-09 21:27 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_transaction.rs
> +    MismatchEntityAndEntityId,
Same thing about the context from the comment on the file above

2024-09-10 16:07 UTC, yulesa commented on crates/core/src/interpreter/frontend/parser.rs
>                  // The grammar and productions should be double checked.
Done

2024-09-10 16:20 UTC, yulesa commented on crates/core/src/interpreter/backend/resolve_logs.rs
> +    // InvalidAddress,
Done!

2024-09-10 16:52 UTC, yulesa commented on crates/core/src/interpreter/backend/resolve_logs.rs
> +        return Err("No logs found".into()); // Check if this is the best approach for no logs return. I understand it shouldn't panic.
Done!

2024-09-10 17:30 UTC, yulesa commented on crates/core/src/interpreter/backend/resolve_logs.rs
> +    MismatchEntityAndEntityId,
Logs can't have a entity_id. I'm not even testing this at this file, I can remove this. Are you suggesting I need to check it?

2024-09-10 17:43 UTC, yulesa commented on crates/core/src/interpreter/backend/resolve_transaction.rs
> +    MismatchEntityAndEntityId,
Done

2024-09-10 19:37 UTC, yulesa commented on crates/core/src/interpreter/backend/execution_engine.rs
> +
I created the `ExecutionEngineError` to fix the TODO.
I've simplified all previous panics to a single Err (NoEntityIdOrFilter), except for the multiple filters in blocks.
Overall I think this shouldn't be here. One idea is to move all these checks to the `resolve_[entity].rs` files by passing both `expr.entity_id` and `expr.entity_filter` to the `resolve_[entity]_query` function. This way, only ` NoEntityIdOrFilter` would be an error here.

2024-09-10 19:39 UTC, yulesa commented on crates/core/src/interpreter/backend/resolve_block.rs
> +        block_futures.push(block_future);
I removed all the comments. I've included docs to the functions; check if you like them.

2024-09-10 19:43 UTC, yulesa commented on crates/core/src/common/entity_id.rs
> +}
To implement an error like:
```
    #[error("Entity id {0} can't be used to identify Log")]
    MismatchEntityAndEntityId(String),
```
I had to implement Display for EntityId, but I'm making it using a mix of Debug mode and hardcoding transaction_hash. I'm not sure if that's okay.

2024-09-10 19:47 UTC, yulesa commented on crates/core/src/interpreter/backend/resolve_logs.rs
> +    MismatchEntityAndEntityId,
This comment is also relevant: https://github.com/iankressin/eql/pull/39#discussion_r1752627826

2024-09-11 13:37 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_block.rs
> +        block_futures.push(block_future);
Yeah, this is way better! Thanks

2024-09-11 14:17 UTC, iankressin commented on crates/core/src/common/entity_id.rs
> +}
We can make this cleaner by implementing `Display` for `BlockRange` and `NameOrAddress`.

```rust
// entity_filter.rs 
impl Display for BlockRange {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        match &self.end {
            Some(end) => write!(f, "{}:{}", self.start, end),
            None => write!(f, "{}", self.start),
        }
    }
}

// ens.rs
impl Display for NameOrAddress {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Name(name) => write!(f, "{}", name),
            Self::Address(addr) => write!(f, "{}", addr),
        }
    }
}
```

Then, the Display method of `EntityId` doesn't need to use any tricks:
```rust
impl Display for EntityId {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        match self {
            EntityId::Block(block_range) => write!(f, "{}", block_range),
            EntityId::Transaction(tx_hash) => write!(f, "{}", tx_hash),
            EntityId::Account(name_or_address) => write!(f, "{}", name_or_address),
        }
    }
}

```

2024-09-11 14:26 UTC, iankressin commented on crates/core/src/interpreter/backend/resolve_logs.rs
> +    MismatchEntityAndEntityId,
I forgot logs doesn't have ids. In this case we need can use a simple message like "Mismatch filters for Logs".

In the future I want to remove all verification between entities and entity ids from the `backend`, this is should happen on the `frontend` only. Therefore we don't need to waste too much time doing analysis of which filter is malformatted right now.

This was a poor design decision from my part.

2024-09-11 14:29 UTC, iankressin commented on crates/core/src/interpreter/backend/execution_engine.rs
> +
We can do this in a separate PR, as this is not critical for this one. But what implemented here is already good enough for the moment.

As I mentioned in a comment, in the future all of this semantic analysis should happen on the `frontend`, and we should rely strictly in Rust's type system here, which implies we wont have to deal with this type of errors in the execution_engine

2024-09-11 19:40 UTC, yulesa commented on crates/core/src/common/entity_id.rs
> +}
Your solution didn't work well for `BlockRange`. It was showing block numbers as hex. I tried to parse them to numbers, but then I couldn't handle the tag (latest). The best solution I found was to make the Display the same as the Debug view.

2024-09-12 12:54 UTC, iankressin commented on crates/core/src/common/entity_id.rs
> +}
Here's a version of `fmt` for `BlockRange` that fixes what you mentioned
```rust
impl Display for BlockRange {
    fn fmt(&self, f: &mut Formatter) -> fmt::Result {
        let start = match &self.start {
            BlockNumberOrTag::Number(number) => number.to_string(),
            _ => self.start.to_string(),
        };

        if let Some(end) = &self.end {
            let end = match end {
                BlockNumberOrTag::Number(number) => number.to_string(),
                _ => end.to_string(),
            };
            write!(f, "{}:{}", start, end)
        } else {
            write!(f, "{}", start)
        }
    }
}
```

And this is test case that proves the correctness of the implementation
```rust
#[cfg(test)]
mod tests {
    use std::str::FromStr;
    use super::*;
    use crate::common::{chain::Chain, entity_filter::BlockRange};
    use alloy::{eips::BlockNumberOrTag, providers::ProviderBuilder};

    #[tokio::test]
    async fn test_error_when_id_doesnt_match_transaction() {
        let fields = vec![]; // Empty fields for simplicity
        let provider = ProviderBuilder::new().on_http(Chain::Sepolia.rpc_url().parse().unwrap());
        let entity_id = EntityId::Block(BlockRange::new(
            10.into(),
            Some(BlockNumberOrTag::from_str("latest").unwrap()),
        ));

        let result = resolve_transaction_query(vec![entity_id], fields, &provider)
            .await
            .unwrap_err()
            .to_string();

        assert_eq!(
            result,
            "Mismatch between Entity and EntityId, 1:latest can't be resolved as a block id"
        );
    }
}
```

2024-09-12 14:19 UTC, merged