Add support to star operator
iankressin/eql pull request #42
Opened 2024-09-06 18:07 UTC by yulesa

# Summary

This PR adds support for a star operator `*` (wildcard operator), which adds all the entity's fields.
Examples:
```
GET * FROM 
  account 
     0x1234567890123456789012345678901234567890
ON eth
```

## Related Issue

Close issue #17 

## Technical details

### productions.pest

### parser.rs

### execution_engine.rs

## PR Checklist

-   [x] Added Tests
-   [x] Cargo Tests Passing
-   [ ] Added Documentation
-   [ ] Breaking changes

## Screenshots (if applicable)

![image](https://github.com/user-attachments/assets/519ed664-b3f2-4021-8c7d-12b7d165babe)

2024-09-09 20:47 UTC, iankressin requested changes

2024-09-09 20:47 UTC, iankressin commented on crates/core/src/interpreter/backend/execution_engine.rs
> +                        vec![
We're missing `BlockField::Number` here, and this is happening because this implementation is loosely typed. 

We don't guarantees that when we a new variant, the compiler will force to update this list. Also this pattern is quite repetitive. 

I've create this PR to your fork, where I implement a procedural macro that basically implements  a macro that adds a function called `all_variants` to any enum we need to list all the fields.
https://github.com/yulesa/eql/pull/1/commits/85d5d98a0d638aad054537722a14c395fcee5a2a

That solves the problem of forgetting to add fields to these lists and we have a more concise implementation.

2024-09-10 20:26 UTC, yulesa commented on crates/core/src/interpreter/backend/execution_engine.rs
> +                        vec![
You've committed to the wrong branch. I've added it here.

2024-09-11 14:32 UTC, iankressin approved these changes

2024-09-11 17:44 UTC, merged